- service-app/internal/aws/client.go
The AWS_ENDPOINT env var allows us to overwrite the default AWS base URL for localstack. But our default behaviour should be not to set an endpoint at all and use whatever the default in the AWS SDK is.
This will help the task start in real AWS environments.
For SSM-20 #patch
An empty/missing AWS_ENDPOINT will be handled as an empty string, and passing that to `Options.BaseEndpoint` is the behaviour that we want.
I noticed that the envconfig package we're using has a `required` tag option that we're not using.
* N/A
* N/A
* N/A
* N/A
* N/A
> Allow empty AWS_ENDPOINT env var

- service-app/config/config.go
- service-app/internal/aws/client.go
The S3 bucket is protected by a CMK, so we need to specify KMS encryption and use the ID of the KMS key (passed in by an env var).
For SSM-15 #patch
> Use KMS encryption when saving objects

- service-app/internal/api/handler.go
Change is to fix the timeout issue in the IngestHandler function within handler.go.
To fix the timeout issue, I added a `context.WithTimeout` call to set a timeout duration for the HTTP call to create a stub case in Sirius. This ensures that the HTTP call does not wait indefinitely for a response, and instead returns an error if the response takes longer than the specified timeout duration.
Additionally, added the `cancel()` function to ensure that the context is cancelled when the function returns, but not before the `CreateCaseStub` call has completed.
Check my context usages properly!
> feat/SSM-31: added context with timeout to avoid hanging requests.

- service-app/internal/api/service.go
- service-app/internal/api/service_documents_test.go
To ensure it's returned for all documents
Fixes SSM-36 #patch
> Set decodedXML a level higher

- service-app/xsd/LP1F.xsd
- service-app/xsd/LP1H.xsd
We want to extract the payment reference, date and amount from the form so we can trace cheque payments in the future.
For SSM-62 #minor
Aligning from ministryofjustice/opg-sirius#10980
`xs:sequence` seems to validate weirdly in PHP, but that isn't a problem for now.
> Add office payment fields to LP1F/H XSD

- service-app/internal/api/handler.go
- service-app/internal/api/service.go
- service-app/internal/constants/document_types.go
- service-app/internal/factory/document_component.go
- service-app/internal/factory/document_factory_test.go
- service-app/internal/factory/document_processor.go
- service-app/internal/parser/corresp_parser/corresp_parser.go
- service-app/internal/parser/lpa120_parser/lpa120_parser.go
- service-app/internal/types/lpa120/lpa120_document.go
- service-app/internal/types/lpa120_types/lpa120_document.go
- service-app/xml/LPA120-valid.xml
- service-app/xml/LPC-valid.xml
Handle LPA120 (reduced Fees) form
Fixes SSM-27
Integrated and reused existing go structs to support LPA120 XSD.
Due to the volume of form types, slightly optimised switch-case to use mapper instead with a getter function which returns the correct instances for parser, validation, and sanitisation.
It appears that the document ingestion at the factory level does not fully support all XML document types. Additional tests have been added for each valid document type in the XML directory.
While adding the additional tests, I noticed that "LPC" document type was missing in 
`SupprotedDocumentTypes = []string{
DocumentTypeLP1F,
DocumentTypeLP1H,
DocumentCorresp,
}`
This implies an underlying bug which has been resolved.
> feat/SSM-27: added lpa120 document type structs.

- docs/pull_request_template.md
- service-app/internal/constants/document_types.go
- service-app/internal/ingestion/set_validator.go
- service-app/internal/ingestion/set_validator_test.go
Rather than requiring instruments and applications to be sent in the same set, allow any document to be sent individually.
But add some new validation rules to protect against confusing circumstances: documents either create cases or they don't, and the presence of `CaseNo` is dependent on there being no case-creators in the set. Also you can't have two case-creators in the same set.
I also got rid of a few constants that are no longer used.
Fixes SSM-63 #major
> Allow documents to be sent separately

- Makefile
- docker-compose.sirius.yml
- docker-compose.yml
- docker/sirius/imposter-config.yaml
- docker/sirius/openapi.yaml
Adds an imposter container that mocks Sirius's behaviour, which removes the requirement for an external network.
This will also allow us to stand up the app in the CI pipeline for testing.
Fixes SSM-19 #minor
But integrating with Sirius is helpful, because it lets us do end-to-end tests and check mapping of the XML document, so I've added an additional `docker-compose.sirius.yml` file which uses (and requires) Sirius to be running locally.
Therefore:
- `make start` allows you to do a minimal local stand-up of the app
- `make start-sirius` requires Sirius to be running locally and lets you ingest documents fully
`!reset null` is really useful!
* N/A
* N/A
* N/A
> Add Sirius mock

- renovate.json
Will run `go mod tidy` to remove unused dependencies from `go.sum`, keeping our dependency files cleaner and reducing false positives in vulnerability scanning tools.
#patch
> Run `gomodTidy` after Renovate PR

- .github/workflows/build.yml
- .gitignore
- Makefile
- docker-compose.yml
- docker/go-lint/Dockerfile
- service-app/internal/api/handler.go
- service-app/internal/api/handler_test.go
- service-app/internal/factory/document_processor.go
- service-app/internal/parser/lp1f_parser/lp1f_validator_test.go
- service-app/internal/parser/lp1h_parser/lp1h_validator_test.go
- service-app/internal/parser/lpc_parser/lpc_validator_test.go
To actively monitor for and alert us to risky code
Also fix some issues raised:
- Always handle `error` return values
- Set `ReadHeaderTimeout` on the HTTP server
#patch
> Add golangci-lint and gosec

- service-app/internal/api/handler.go
More robust validation added using `hasPrefix` to check beginning of header value matches expectation.
Fixes SSM-80
> feat/SSM-80: added HasPrefix check to content-type header validation

- service-app/internal/api/handler.go
`loggerCtx` was created by extending the existing context, but this gets cancelled before the queued job is executed.
Fixes SSM-81 #patch
Create a new context and attach the logger/timeout to it.
> Stop reusing context

- service-app/internal/api/handler.go
- service-app/internal/api/handler_test.go
- service-app/internal/factory/document_processor.go
- Pass `uid` as a log argument rather than trying to substitute it into the message (which isn't working)
- Log validation and 4xx errors at INFO level. ERROR level is reserved from problems with the service since it triggers on-call alarms
Fixes SSM-85 #patch
> Logging improvements

- .github/workflows/build.yml
- Makefile
- docker-compose.yml
- docker/sirius/imposter-config.yaml
- docker/sirius/scanned-cases-endpoint.js
- scripts/localstack/wait/healthcheck.sh
- service-app/internal/constants/document_types.go
- service-app/xml/Correspondence-valid.xml
- service-app/xml/LPA120-valid.xml
- service-app/xml/LPC-valid.xml
- tester/test.sh
Add an integration test script to be run in the pipeline and check the application works correctly.
Fixes SSM-72 #minor
Starts up the application and sends example files to it to check the are correctly parsed.
For files which create cases, it also checks that a message has been added to the SQS queue.
I updated the Sirius mock to generate unique UIDs on each request, which is used to ensure the SQS message relates to the most recent file.
Fixed a few issues with our existing test files.
Removed LPA002 and LPA002R from `NewCaseDocuments`, as they should be supplied alongside LP2s which create the case.
Bash really mangled the output of the SQS message, stripping away slashes that made it invalid JSON. I avoided this in the end by doing all the manipulation in one `jq` statement, but it …
> Add integration test script

- service-app/internal/factory/document_processor.go
- service-app/internal/parser/corresp_parser/corresp_validator.go
- service-app/internal/parser/ep2pg_parser/ep2pg_validator.go
- service-app/internal/parser/ep2pg_parser/ep2pg_validator_test.go
- service-app/internal/parser/interface.go
- service-app/internal/parser/lp1f_parser/lp1f_validator.go
- service-app/internal/parser/lp1f_parser/lp1f_validator_test.go
- service-app/internal/parser/lp1h_parser/lp1h_validator.go
- service-app/internal/parser/lp1h_parser/lp1h_validator_test.go
- service-app/internal/parser/lp2_parser/lp2_validator.go
- service-app/internal/parser/lp2_parser/lp2_validator_test.go
- service-app/internal/parser/lpc_parser/lpc_validator.go
- service-app/internal/parser/lpc_parser/lpc_validator_test.go
- service-app/internal/parser/validator.go
- service-app/internal/parser/validator_test_helper.go
- service-app/xml/LP1F-invalid-dates.xml
Consolidate validation test logic into reusable handler 
Fixes SSM-86
Introduce test helper function for all document type validation assertions, `GetValidatorErrorMessages` method added to interface as a result to facilitate the abstraction.
> feat/SSM-86: initial commit consolidating validation test logic

- service-app/internal/constants/document_types.go
- service-app/internal/ingestion/set_validator.go
"NewCaseDocuments" was a bit off as a grouping. We only use it to care about whether the Set should have a CaseNo, which COPORDs should (it should be the court reference number).
Therefore, rename the set variable name to be more accurate and remove COPORD from the set.
#patch
> Require CaseNo on COPORDs

- service-app/internal/api/handler.go
- service-app/internal/api/handler_test.go
If `<Document Type="X">` refers to a type that we don't support, this is only picked up in the internal queue. This means the user gets a 200 response back even though the Set XML isn’t valid.
Fixes SSM-101 #minor
Add a check during initial validation of the documents in the set.
* N/A
* N/A
> Front-load document type errors

- service-app/internal/api/handler.go
- service-app/internal/auth/middleware_mock.go
- service-app/internal/aws/client.go
- service-app/internal/aws/client_mock.go
- service-app/internal/aws/client_test.go
For easier debugging of issues
Fixes SSM-103 #minor
Saves the Set file as soon as possible (after we know it's valid string, before any validation/processing). It will automatically be deleted after 14 days.
> Save Set file to jobsqueue bucket

- service-app/internal/api/handler.go
- service-app/internal/ingestion/job_queue.go
- service-app/internal/ingestion/job_queue_test.go
Add configurable HTTP timeouts in worker queue
Fixes SSM-108
> feat/SSM-108: implemented todo so that http timeouts remain consistent.

- service-app/internal/ingestion/xsd_validator.go
When using libxml2 for XSD validation, we must pass an option NONET to disable external entity processing
Fixes SSM-113
> added XMLParseNoNet to libxml2.ParseString

- service-app/internal/ingestion/job_queue.go
The HTTP request within the onComplete callback is executed using the original context `job.ctx`, not the timeout-enforced `processCtx`. This means that when the timeout expires, the HTTP client times out and returns an error, but the request to Sirius doesnt receive the cancellation signal. This mismatch causes the downstream request to continue processing without respecting timeout.
Fixes SSM-119
> feat/SSM-119: ensure correct timeout is propagated.

- service-app/internal/api/processor.go
- service-app/internal/api/service_cases_test.go
- service-app/internal/constants/document_types.go
- service-app/internal/ingestion/set_validator.go
The scanning app looks at `EPATypeDocuments` and `LPATypeDocuments` when determining whether to create a case, meaning it creates new stubs for EPA and LPA002 documents rather than attaching them to the existing case.
We need to only create cases for LP1F, LP1H, LP2 and EP2PG cases.
Fixes SSM-139 #patch
Rather than looking at `LPATypeDocuments`/`EPATypeDocuments` for determining when to create case stubs, and `NewCaseNumberDocuments` when validating the document, centralise the constants into `CreateLPADocuments` and `CreateEPADocuments`.
Also, remove LPA002 and EPA from the lists since they should not create new cases.
We should have centralised this logic sooner.
* N/A
* N/A
* I've fixed and expanded existing tests
> Simplify case creation rules

- service-app/internal/api/index_controller.go
- service-app/internal/api/queue_handler.go
- service-app/internal/aws/client.go
If a document already exists with the same key, fail the request so it can be requeued.
Ensure ProcessQueue returns errors and use a friendly message in the response body.
For SSM-143 #minor
> Don't overwrite documents in jobsqueue bucket

- service-app/internal/api/index_controller.go
- service-app/internal/api/index_controller_test.go
- service-app/internal/sirius/client.go
If Sirius returns a 413 error, return that status code to the client and give them a clearer error message.
Fixes SSM-154 #patch
Expand existing pattern for other 4xx errors
* N/A
* N/A
> Handle 413 responses form Sirius better
